language: php
php:
  - 7.2
  - 7.1
  - 7.0

dist: trusty
sudo: required

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email: false