language: php
php:
    - 7.1
    - 7.0
    - 5.6
    - hhvm

sudo: false

before_script:
    - composer install

script:
    - mkdir -p build/logs
    - phpunit

after_success:
    - travis_retry php vendor/bin/coveralls

notifications:
    email: false